spring:
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    config:
        import: "classpath:/swapi-endpoints.yml"
    web:
        locale: en
jwt:
    secret: ${JWT_SECRET:default-secret}
    expiration: 600000
server:
    port: ${SERVER_PORT:8080}
deployment:
    url: ${DEPLOYMENT_URL:http://localhost:${server.port}}

#logging:
#    level:
#        org:
#            springframework:
#                web:
#                    client:
#                        RestTemplate: DEBUG
#        springfox:
#            documentation: DEBUG